import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/app/providers";
import Header from "@/components/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body>
        <Providers>
          <Header />
          <main className="p-8 flex flex-col">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
